### ISSUE TITLE
vue3+vite  deploy production. Error: unable to open window  and null is not an object(evaluating windowRef.closed)

### ISSUE THREAD

**Issue by NickBoomBoom** [Web3Auth/Web3Auth#248]
### **Describe the bug**

vue3+vite  deploy production. Error: unable to open window  and null is not an object(evaluating windowRef.closed)

i use vue3  + vite (3.0.0-beta.5)  build project.

mobile test 

in login modal , 
1. click Google login
2. Error: unable to open window 
3. Try it again
4. open the new window  success 
5. login success 
6. Error: null is not an object(evaluating windowRef.closed)

### **Device Info (please complete the following information):**

- Device: Iphone 13pro
- OS: ios 15.5
- Browser  safari 
- Web3Auth Version 1.1.0
- Vite 3.0.0-beta.5
- Vue 3.2.37

Can you help me ?

I don`t know what happened

**Comment by skambalin** [comment]
Hello,
I have the same issue on Mobile Safari. For the first attempt the popup is blocked, but the second attempt is successful.

My guess that the issue is related to the async import of `privKeyProvider` implementation, which makes first attempt asynchronous and leads to the popup blocking. But since the provider implementation is already loaded for the second attempt - the flow is synchronous and therefore the popup is not blocked by the browser. 

https://github.com/Web3Auth/Web3Auth/blob/master/packages/adapters/openlogin-adapter/src/openloginAdapter.ts#L189

**Comment by skambalin** [comment]
The quick fix for the issue is to preload an appropriate `privKeyProvider` (in my case `ethereum-provider`) somewhere in advance:

```ts
import("@web3auth/ethereum-provider");
```

**Comment by NickBoomBoom** [comment]
> The quick fix for the issue is to preload an appropriate `privKeyProvider` (in my case `ethereum-provider`) somewhere in advance:
> 
> ```ts
> import("@web3auth/ethereum-provider");
> ```

Thank you for your answer.
But it doesn't work for me.
![image](https://user-images.githubusercontent.com/29225479/180266758-058fc290-ad96-480d-9812-b4af3f949ead.png)
I use UX_MODE.REDIRECT

**Comment by MagiCalcifer** [comment]
Hey there. I was stumbled upon this same issue. I was using the core module, and it turns out if you try to initiate Metamask adapter when Metamask was not installed in the first place, the whole thing got stuck, you can't use open login this way. My solution was to simply check if window.etheruem is available, only then call the configureAdapter method.
